### PR TITLE
Jess/documentation

### PR DESCRIPTION
**Pull request by ellojess**
## Description

I added some standard open source documentation for when others might be interested in contributing to the project further down the line including a CODE_OF_CONDUCT and CONTRIBUTING MD files (definitely feel free to update. it as you see fit). More information can be found [here](https://opensource.guide/starting-a-project/) on setting up open source projects. 

## Type of change

- [x] Documentation updates

## TODOs

I think it would be beneficial to add a section in README for possible items and features others can work on if they were interested in contributing as well. I know I would be interested in hearing more about what you had in mind for additional features and items. 

Looking forward to hearing your thoughts again! Its been a blast so far 🤗

### CODE REVIEW

**Comment by simonboots** [comment]
Thanks for the PR! 🥳

**Comment by simonboots** [comment]
Looks good, thanks @ellojess! There are two `.DS_Store` files that have snuck in. I should have updated the `.gitignore` file and excluded them. If you could remove these two files that would be great!

**Comment by ellojess** [comment]
Great catch @simonboots - I went ahead and added .DS_Store to the .gitignore file. Do you mind me asking how you caught that? I'm very impressed! It slipped right by me

**Comment by simonboots** [comment]
@ellojess Awesome, thanks a lot! I usually start reviewing PRs by looking at the "Files changed" tab. That's where I saw those two files.
Screen Shot 2021-03-05 at 5 17 08 pm

**Pull request merged**
